// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { add } from "./add.js";
import { create } from "./create.js";
import { dispose } from "./dispose.js";
import { find } from "./find.js";
import { includes } from "./includes.js";
import { isDisposed } from "./isDisposed.js";
import { isDsp } from "./isDsp.js";
import { remove } from "./remove.js";
import { symbol } from "./symbol.js";
import { unlink } from "./unlink.js";

interface Dsp extends Disposable {
    dsps: DspLink | undefined
    [symbol]: boolean
    vals: DspLink | undefined
}

type DspValue = (() => void) | Dsp | Disposable

interface DspLink {
    disposer: Dsp
    nextDsp: DspLink | undefined
    nextVal: DspLink | undefined
    prevDsp: DspLink | undefined
    prevVal: DspLink | undefined
    val: DspValue
}

declare namespace Dsp {
    export {
        add,
        create,
        dispose,
        find,
        includes,
        isDisposed,
        isDsp,
        remove,
        symbol,
        unlink,
    }
}

export {
    Dsp,
    DspLink,
    DspValue,
}
