// Generated by scripts/manifest.ts

/** The namespaces of @monstermann/fn, each member is a file of the same name. */
export const namespaces: ReadonlySet<string> = new Set([
    "Arr",
    "Async",
    "Dll",
    "Dsp",
    "Maps",
    "Num",
    "Obj",
    "Rect",
    "Sets",
    "Str",
])

/** The other exports of @monstermann/fn and the files they are exported from. */
export const files: Readonly<Record<string, string>> = {
    cloneArray: "remmi/cloneArray",
    cloneMap: "remmi/cloneMap",
    cloneObject: "remmi/cloneObject",
    cloneSet: "remmi/cloneSet",
    dfdl: "dfdl/dfdl",
    dfdlT: "dfdl/dfdlT",
    endMutations: "remmi/endMutations",
    flow: "dfdl/flow",
    isImmutable: "remmi/isImmutable",
    isMutable: "remmi/isMutable",
    isMutating: "remmi/isMutating",
    markAsImmutable: "remmi/markAsImmutable",
    markAsMutable: "remmi/markAsMutable",
    match: "match/match",
    pauseMutations: "remmi/pauseMutations",
    pipe: "dfdl/pipe",
    startMutations: "remmi/startMutations",
    withMutations: "remmi/withMutations",
}
