// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { debounce } from "./debounce.js";
import { Debounced } from "./debounce.js";
import { limit } from "./limit.js";
import { Limited } from "./limit.js";
import { queue } from "./queue.js";
import { throttle } from "./throttle.js";
import { Throttled } from "./throttle.js";
import { wait } from "./wait.js";

declare namespace Async {
    export {
        debounce,
        limit,
        queue,
        throttle,
        wait,
    }
}

export {
    Async,
    Debounced,
    Limited,
    Throttled,
}
