// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { debounce } from "./debounce.js";
import { limit } from "./limit.js";
import { queue } from "./queue.js";
import { throttle } from "./throttle.js";
import { wait } from "./wait.js";

export const Async = {
    debounce,
    limit,
    queue,
    throttle,
    wait,
}
