// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { append } from "./append.js";
import { at } from "./at.js";
import { atOr } from "./atOr.js";
import { atOrElse } from "./atOrElse.js";
import { atOrThrow } from "./atOrThrow.js";
import { clone } from "./clone.js";
import { compact } from "./compact.js";
import { concat } from "./concat.js";
import { countBy } from "./countBy.js";
import { create } from "./create.js";
import { drop } from "./drop.js";
import { dropLast } from "./dropLast.js";
import { empty } from "./empty.js";
import { every } from "./every.js";
import { filter } from "./filter.js";
import { find } from "./find.js";
import { findIndex } from "./findIndex.js";
import { findIndexOr } from "./findIndexOr.js";
import { findIndexOrElse } from "./findIndexOrElse.js";
import { findIndexOrThrow } from "./findIndexOrThrow.js";
import { findLast } from "./findLast.js";
import { findLastIndex } from "./findLastIndex.js";
import { findLastIndexOr } from "./findLastIndexOr.js";
import { findLastIndexOrElse } from "./findLastIndexOrElse.js";
import { findLastIndexOrThrow } from "./findLastIndexOrThrow.js";
import { findLastOr } from "./findLastOr.js";
import { findLastOrElse } from "./findLastOrElse.js";
import { findLastOrThrow } from "./findLastOrThrow.js";
import { findMap } from "./findMap.js";
import { findMapAll } from "./findMapAll.js";
import { findMapLast } from "./findMapLast.js";
import { findMapLastOr } from "./findMapLastOr.js";
import { findMapLastOrElse } from "./findMapLastOrElse.js";
import { findMapLastOrThrow } from "./findMapLastOrThrow.js";
import { findMapOr } from "./findMapOr.js";
import { findMapOrElse } from "./findMapOrElse.js";
import { findMapOrThrow } from "./findMapOrThrow.js";
import { findOr } from "./findOr.js";
import { findOrElse } from "./findOrElse.js";
import { findOrThrow } from "./findOrThrow.js";
import { findRemove } from "./findRemove.js";
import { findRemoveLast } from "./findRemoveLast.js";
import { findRemoveLastOr } from "./findRemoveLastOr.js";
import { findRemoveLastOrElse } from "./findRemoveLastOrElse.js";
import { findRemoveLastOrThrow } from "./findRemoveLastOrThrow.js";
import { findRemoveOr } from "./findRemoveOr.js";
import { findRemoveOrElse } from "./findRemoveOrElse.js";
import { findRemoveOrThrow } from "./findRemoveOrThrow.js";
import { findReplace } from "./findReplace.js";
import { findReplaceLast } from "./findReplaceLast.js";
import { findReplaceLastOr } from "./findReplaceLastOr.js";
import { findReplaceLastOrElse } from "./findReplaceLastOrElse.js";
import { findReplaceLastOrThrow } from "./findReplaceLastOrThrow.js";
import { findReplaceOr } from "./findReplaceOr.js";
import { findReplaceOrElse } from "./findReplaceOrElse.js";
import { findReplaceOrThrow } from "./findReplaceOrThrow.js";
import { first } from "./first.js";
import { firstOr } from "./firstOr.js";
import { firstOrElse } from "./firstOrElse.js";
import { firstOrThrow } from "./firstOrThrow.js";
import { flatMap } from "./flatMap.js";
import { forEach } from "./forEach.js";
import { forEachRight } from "./forEachRight.js";
import { groupBy } from "./groupBy.js";
import { includes } from "./includes.js";
import { includesAll } from "./includesAll.js";
import { includesAny } from "./includesAny.js";
import { includesNone } from "./includesNone.js";
import { indexBy } from "./indexBy.js";
import { indexOf } from "./indexOf.js";
import { indexOfOr } from "./indexOfOr.js";
import { indexOfOrElse } from "./indexOfOrElse.js";
import { indexOfOrThrow } from "./indexOfOrThrow.js";
import { insertAllAt } from "./insertAllAt.js";
import { insertAllAtOr } from "./insertAllAtOr.js";
import { insertAllAtOrElse } from "./insertAllAtOrElse.js";
import { insertAllAtOrThrow } from "./insertAllAtOrThrow.js";
import { insertAt } from "./insertAt.js";
import { insertAtOr } from "./insertAtOr.js";
import { insertAtOrElse } from "./insertAtOrElse.js";
import { insertAtOrThrow } from "./insertAtOrThrow.js";
import { is } from "./is.js";
import { isEmpty } from "./isEmpty.js";
import { isShallowEqual } from "./isShallowEqual.js";
import { join } from "./join.js";
import { last } from "./last.js";
import { lastIndexOf } from "./lastIndexOf.js";
import { lastIndexOfOr } from "./lastIndexOfOr.js";
import { lastIndexOfOrElse } from "./lastIndexOfOrElse.js";
import { lastIndexOfOrThrow } from "./lastIndexOfOrThrow.js";
import { lastOr } from "./lastOr.js";
import { lastOrElse } from "./lastOrElse.js";
import { lastOrThrow } from "./lastOrThrow.js";
import { length } from "./length.js";
import { mapAt } from "./mapAt.js";
import { mapAtOr } from "./mapAtOr.js";
import { mapAtOrElse } from "./mapAtOrElse.js";
import { mapAtOrThrow } from "./mapAtOrThrow.js";
import { mapEach } from "./mapEach.js";
import { maxOr } from "./maxOr.js";
import { maxOrElse } from "./maxOrElse.js";
import { maxOrThrow } from "./maxOrThrow.js";
import { meanOr } from "./meanOr.js";
import { meanOrElse } from "./meanOrElse.js";
import { meanOrThrow } from "./meanOrThrow.js";
import { medianOr } from "./medianOr.js";
import { medianOrElse } from "./medianOrElse.js";
import { medianOrThrow } from "./medianOrThrow.js";
import { minOr } from "./minOr.js";
import { minOrElse } from "./minOrElse.js";
import { minOrThrow } from "./minOrThrow.js";
import { none } from "./none.js";
import { partition } from "./partition.js";
import { prepend } from "./prepend.js";
import { random } from "./random.js";
import { randomOr } from "./randomOr.js";
import { randomOrElse } from "./randomOrElse.js";
import { reduce } from "./reduce.js";
import { reject } from "./reject.js";
import { remove } from "./remove.js";
import { removeAll } from "./removeAll.js";
import { removeAt } from "./removeAt.js";
import { removeAtOr } from "./removeAtOr.js";
import { removeAtOrElse } from "./removeAtOrElse.js";
import { removeAtOrThrow } from "./removeAtOrThrow.js";
import { removeLast } from "./removeLast.js";
import { removeLastOr } from "./removeLastOr.js";
import { removeLastOrElse } from "./removeLastOrElse.js";
import { removeLastOrThrow } from "./removeLastOrThrow.js";
import { removeOrElse } from "./removeOrElse.js";
import { removeOrThrow } from "./removeOrThrow.js";
import { replace } from "./replace.js";
import { replaceLast } from "./replaceLast.js";
import { replaceLastOr } from "./replaceLastOr.js";
import { replaceLastOrElse } from "./replaceLastOrElse.js";
import { replaceLastOrThrow } from "./replaceLastOrThrow.js";
import { replaceOr } from "./replaceOr.js";
import { replaceOrElse } from "./replaceOrElse.js";
import { replaceOrThrow } from "./replaceOrThrow.js";
import { setAt } from "./setAt.js";
import { setAtOr } from "./setAtOr.js";
import { setAtOrElse } from "./setAtOrElse.js";
import { setAtOrThrow } from "./setAtOrThrow.js";
import { shuffle } from "./shuffle.js";
import { slice } from "./slice.js";
import { some } from "./some.js";
import { sort } from "./sort.js";
import { splice } from "./splice.js";
import { sum } from "./sum.js";
import { take } from "./take.js";
import { takeLast } from "./takeLast.js";
import { union } from "./union.js";
import { unique } from "./unique.js";

declare namespace Arr {
    export {
        append,
        at,
        atOr,
        atOrElse,
        atOrThrow,
        clone,
        compact,
        concat,
        countBy,
        create,
        drop,
        dropLast,
        empty,
        every,
        filter,
        find,
        findIndex,
        findIndexOr,
        findIndexOrElse,
        findIndexOrThrow,
        findLast,
        findLastIndex,
        findLastIndexOr,
        findLastIndexOrElse,
        findLastIndexOrThrow,
        findLastOr,
        findLastOrElse,
        findLastOrThrow,
        findMap,
        findMapAll,
        findMapLast,
        findMapLastOr,
        findMapLastOrElse,
        findMapLastOrThrow,
        findMapOr,
        findMapOrElse,
        findMapOrThrow,
        findOr,
        findOrElse,
        findOrThrow,
        findRemove,
        findRemoveLast,
        findRemoveLastOr,
        findRemoveLastOrElse,
        findRemoveLastOrThrow,
        findRemoveOr,
        findRemoveOrElse,
        findRemoveOrThrow,
        findReplace,
        findReplaceLast,
        findReplaceLastOr,
        findReplaceLastOrElse,
        findReplaceLastOrThrow,
        findReplaceOr,
        findReplaceOrElse,
        findReplaceOrThrow,
        first,
        firstOr,
        firstOrElse,
        firstOrThrow,
        flatMap,
        forEach,
        forEachRight,
        groupBy,
        includes,
        includesAll,
        includesAny,
        includesNone,
        indexBy,
        indexOf,
        indexOfOr,
        indexOfOrElse,
        indexOfOrThrow,
        insertAllAt,
        insertAllAtOr,
        insertAllAtOrElse,
        insertAllAtOrThrow,
        insertAt,
        insertAtOr,
        insertAtOrElse,
        insertAtOrThrow,
        is,
        isEmpty,
        isShallowEqual,
        join,
        last,
        lastIndexOf,
        lastIndexOfOr,
        lastIndexOfOrElse,
        lastIndexOfOrThrow,
        lastOr,
        lastOrElse,
        lastOrThrow,
        length,
        mapAt,
        mapAtOr,
        mapAtOrElse,
        mapAtOrThrow,
        mapEach,
        maxOr,
        maxOrElse,
        maxOrThrow,
        meanOr,
        meanOrElse,
        meanOrThrow,
        medianOr,
        medianOrElse,
        medianOrThrow,
        minOr,
        minOrElse,
        minOrThrow,
        none,
        partition,
        prepend,
        random,
        randomOr,
        randomOrElse,
        reduce,
        reject,
        remove,
        removeAll,
        removeAt,
        removeAtOr,
        removeAtOrElse,
        removeAtOrThrow,
        removeLast,
        removeLastOr,
        removeLastOrElse,
        removeLastOrThrow,
        removeOrElse,
        removeOrThrow,
        replace,
        replaceLast,
        replaceLastOr,
        replaceLastOrElse,
        replaceLastOrThrow,
        replaceOr,
        replaceOrElse,
        replaceOrThrow,
        setAt,
        setAtOr,
        setAtOrElse,
        setAtOrThrow,
        shuffle,
        slice,
        some,
        sort,
        splice,
        sum,
        take,
        takeLast,
        union,
        unique,
    }
}

export {
    Arr,
}
