import { readdir } from "node:fs/promises"
import Path from "node:path"

const src = Path.resolve(import.meta.dirname, "../../fn/src")
const index = await Bun.file(Path.join(src, "index.ts")).text()

export const namespaces: string[] = []
export const files: Record<string, string> = {}

for (const [, path] of index.matchAll(/export \* from "\.\/(.+)";/g)) {
    // ./Arr/index
    if (await Bun.file(Path.join(src, `${path}.js`)).exists()) {
        namespaces.push(Path.dirname(path!))
        continue
    }

    // ./remmi/index, ./match/match
    const dir = Path.dirname(path!)
    const names = path!.endsWith("/index")
        ? (await readdir(Path.join(src, dir))).filter(name => name.endsWith(".ts") && name !== "index.ts").map(name => name.slice(0, -3))
        : [Path.basename(path!)]
    const exported = new Set(Object.keys(await import(Path.join(src, `${path}.ts`))))

    for (const name of names) {
        for (const key of Object.keys(await import(Path.join(src, dir, `${name}.ts`)))) {
            if (exported.has(key)) files[key] = `${dir}/${name}`
        }
    }
}

const manifest = `// Generated by scripts/manifest.ts

/** The namespaces of @monstermann/fn, each member is a file of the same name. */
export const namespaces: ReadonlySet<string> = new Set(${JSON.stringify(namespaces.sort(), null, 4)})

/** The other exports of @monstermann/fn and the files they are exported from. */
export const files: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(Object.entries(files).sort()), null, 4)}
`

if (import.meta.main) {
    await Bun.write(Path.resolve(import.meta.dirname, "../src/manifest.ts"), manifest)
}
